exclude: ^custom_components/robovac_mqtt/proto/
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py313-plus]
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((custom_components|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=hass,alot,datas,dof,dur,ether,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,rime,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing,iam,incomfort,ba,haa,parm
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
        exclude: ^tests/fixtures/
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        files: ^(custom_components|homeassistant|script|tests)/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^custom_components/.+\.py$
        args: ["--ignore-missing-imports", "--disable-error-code=call-arg,redundant-cast"]
        additional_dependencies:
          - types-protobuf
          - types-requests
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: ^custom_components/.+\.py$
        args: ["-rn", "-sn", "--rcfile=pyproject.toml"]
