# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/realtime_stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/cloud/realtime_stream.proto\x12\x0bproto.cloud"v\n\x11PositionTelemetry\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\x0f\n\x07battery\x18\x02 \x01(\r\x12\x13\n\x0bunknown_seq\x18\x03 \x01(\r\x12\t\n\x01x\x18\x04 \x01(\x11\x12\t\n\x01y\x18\x05 \x01(\x11\x12\x12\n\nextra_data\x18\x06 \x01(\x0c"\x5c\n\x10TelemetryWrapper\x12\x16\n\x0elifetime_stats\x18\x02 \x01(\x0c\x12\x30\n\x08position\x18\x07 \x01(\x0b\x32\x1e.proto.cloud.PositionTelemetry"z\n\x0eRealtimeStream\x12+\n\x04data\x18\x02 \x01(\x0b\x32\x1d.proto.cloud.TelemetryWrapper\x12\x1d\n\x15session_summary_short\x18\x0b \x01(\x0c\x12\x1c\n\x14session_summary_long\x18\r \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.realtime_stream_pb2', globals())
PositionTelemetry = globals()["PositionTelemetry"]
TelemetryWrapper = globals()["TelemetryWrapper"]
RealtimeStream = globals()["RealtimeStream"]
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  PositionTelemetry._serialized_start=50
  PositionTelemetry._serialized_end=168
  TelemetryWrapper._serialized_start=170
  TelemetryWrapper._serialized_end=262
  RealtimeStream._serialized_start=264
  RealtimeStream._serialized_end=386
# @@protoc_insertion_point(module_scope)
